name: Pipeline de CI - TechFlow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Executar testes automatizados
      run: |
        python -m unittest discover -s tests
